### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by theishiopian** [robotv56/kaiju_contact#3]
- [ ] Reload HUD

- [ ] Health UI

- [ ] Iceberg melting

- [ ] Higher railgun aiming

- [ ] faster stopping

- [ ] nerf kaiju

- [ ] MISSILES

**Comment by theishiopian** [comment]
- [ ] splash for shells

- [ ] railgun muzzle flare
